spring:
  application:
    name: gateway-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888/
      enabled: false
    gateway:
      global cors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Origin
              - X-Requested-With
              - Content-Type
              - Accept
              - Authorization
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/users/**
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/accounts/**

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true
info:
  app:
    name: Gateway
    description: API gateway from github
    version: 1.0.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8084